### ISSUE TITLE
Failed to get_profile and then push_message

### ISSUE THREAD

**Issue by axblueblader** [nanato12/line-bot-sdk-rust#23]
First off, thanks for developing this library. When using it I encountered this problem:

I have some code that looks like this. All info are valid.
The ```bot.push_message``` call will fail with 400.
If I remove the ```bot.get_profile``` call then the ```bot.push_message``` call will work correctly.
``` rust
    let line_id = "UXXXXXXXXXXXXXXXXXXXXX";
    let bot = LineBot::new(channel_secret.as_str(), access_token.as_str());
    let mut messages: Vec<SendMessageType> = Vec::new();
    let res = bot.get_profile(line_id);
    let _profile = res.unwrap();
    messages.push(SendMessageType::TextMessage(TextMessage {
        text: String::from("Pushed"),
        emojis: None,
    }));
    let result = bot.push_message(line_id, messages);
```
I'm new to rust so I haven't found out why this happens yet.

**Comment by nanato12** [comment]
thanks @axblueblader 
please show me the error message when it fails.

**Comment by axblueblader** [comment]
Hi @nanato12 , here is the response log
```rust
Ok(Response { url: Url { scheme: "https", username: "", password: None, host: Some(Domain("api.line.me")), port: None, path: "/v2/bot/message/push", query: None, fragment: None
    }, status: 400, headers: {
        "server": "AkamaiGHost",
        "mime-version": "1.0",
        "content-type": "text/html",
        "content-length": "216",
        "expires": "Thu, 15 Apr 2021 06:36:28 GMT",
        "date": "Thu, 15 Apr 2021 06:36:28 GMT",
        "connection": "close"
    }
})
```

**Comment by nanato12** [comment]
add "println" and check the response message.
and show me.

```
let result = bot.push_message(line_id, messages);
println!("{:?}", result.unwrap().text());
```

<img width="692" alt="scchot" src="https://user-images.githubusercontent.com/49806926/114842751-1d1e6d80-9e14-11eb-9cf8-0ca9fdc493ec.png">

UserID length is 33.

if length is not 33, response is `Ok("{\"message\":\"The property, \'to\', in the request body is invalid (line: -, column: -)\"}")`.
if UserId is invalid, response is `Ok("{\"message\":\"Failed to send messages\"}")`

**Comment by axblueblader** [comment]
```
    println!("user id length: {:?}", line_id.len());
    let _res = bot.push_message(line_id, messages);
    println!("bot.push_message: {:?}", _res.unwrap().text());
```
Length is 33
Here is response text
```
Ok("<HTML><HEAD>\n<TITLE>Bad Request</TITLE>\n</HEAD><BODY>\n<H1>Bad Request</H1>\nYour browser sent a request that this server could not understand.<P>\nReference&#32;&#35;7&#46;6fb42d17&#46;1618478740&#46;0\n</BODY>\n</HTML>\n")
```

**Comment by nanato12** [comment]
`LINE_CHANNEL_SECRET` and `LINE_CHANNEL_ACCESS_TOKEN` is correct?

**Comment by axblueblader** [comment]
Yes all info are guaranteed to be correct.
Because this will work:
```rust
    let bot = LineBot::new(channel_secret.as_str(), access_token.as_str());
    let mut messages: Vec<SendMessageType> = Vec::new();
    messages.push(SendMessageType::TextMessage(TextMessage {
        text: String::from("Pushed"),
        emojis: None,
    }));
    let result = bot.push_message(line_id, messages);
```
But this will fail with that error:
```rust
    let bot = LineBot::new(channel_secret.as_str(), access_token.as_str());
    let mut messages: Vec<SendMessageType> = Vec::new();
    
    let res = bot.get_profile(line_id);
    let _profile = res.unwrap();

    messages.push(SendMessageType::TextMessage(TextMessage {
        text: String::from("Pushed"),
        emojis: None,
    }));
    let result = bot.push_message(line_id, messages);
```

**Comment by axblueblader** [comment]
I think it might a bug in the http client or reqwest http client lib.
When debugging, if I step slowly through each function in the debugger, the push_message call will be successful.
Running normally will always get 400.
Hope this info is useful

**Comment by nanato12** [comment]
thanks @axblueblader 
It works without any trouble in my environment.
I don't know the exact cause.
Sorry....

**Comment by axblueblader** [comment]
ye, it could be the Rust version or something
anyways thanks for looking into it
