### ISSUE TITLE
`SouceType` should `SourceType`

### ISSUE THREAD

**Issue by surfertas** [nanato12/line-bot-sdk-rust#27]
https://github.com/nanato12/line-bot-sdk-rust/blob/a5ca302a98f30c11315ce38f7117b7aaf49099ff/src/events/source.rs#L6

Seems like a small mistype. I can open a PR, if needed. Enum naming needs to fixed as well.

**Comment by nanato12** [comment]
thanks @surfertas. 
I will fix that right away.
